#include <stdio.h>
#include <windows.h>
#include <stdlib.h>
int main()
{
    printf("o\n");
    printf("|\n");
    printf("|\n");
    Sleep(500);
    system("cls");
    printf(" o\n");
    printf(" |\\\n");
    printf(" /\n");
    Sleep(500);
    system("cls");
    printf("  o\n");
    printf(" /|\n");
    printf("  \\\n");
    Sleep(500);
    system("cls");
    printf("   o\n");
    printf("   |\\\n");
    printf("   /\n");
    Sleep(500);
    system("cls");
    printf("    o\n");
    printf("   /|\n");
    printf("    \\\n");
    Sleep(500);
    system("cls");
    printf("     o\n");
    printf("     |\\\n");
    printf("     /\n");
    Sleep(500);
    system("cls");
    printf("      o\n");
    printf("     /|\n");
    printf("      \\\n");
    Sleep(500);
    system("cls");
    printf("       o\n");
    printf("       |\\\n");
    printf("       /\n");
    Sleep(500);
    system("cls");
    printf("        o\n");
    printf("       /|\n");
    printf("        \\\n");
    Sleep(500);
    system("cls");
    printf("         o\n");
    printf("         |\\\n");
    printf("         /\n");
    Sleep(500);
    system("cls");
    printf("          o\n");
    printf("         /|\n");
    printf("          \\\n");
    Sleep(500);
    system("cls");
    printf("           o\n");
    printf("           |\\\n");
    printf("           /\n");
    Sleep(500);
    system("cls");
    printf("            o\n");
    printf("           /|\n");
    printf("            \\\n");
    Sleep(500);
    system("cls");
    printf("             o\n");
    printf("             |\\\n");
    printf("             /\n");
    Sleep(500);
    system("cls");
    printf("              o\n");
    printf("             /|\n");
    printf("              \\\n");
    Sleep(500);
    system("cls");
    printf("               \\\n");
    printf("               --o\n");
    printf("              \\\n");
        Sleep(500);
    system("cls");
    printf("               |\n");
    printf("              /|\n");
    printf("               o\n");
        Sleep(500);
    system("cls");
    printf("               /\n");
    printf("              o--\n");
    printf("               \\\n");
        Sleep(500);
    system("cls");
    printf("               o\n");
    printf("              /|\n");
    printf("               |\n");
    return 0;
}

//try loop might work
